### ISSUE TITLE
Limit PushOptions Header sent for a push promise

### ISSUE THREAD

**Issue by jeromegn** [romainmenke/pusher#60]
According to the golang http2 push blog post (https://blog.golang.org/h2push), headers for the push promise should only contain keys and values that will vary the content of the push.

> The second argument to Push specifies additional headers to include in the PUSH_PROMISE. For example, if the response to /app.js varies on Accept-Encoding, then the PUSH_PROMISE should include an Accept-Encoding value

Right now, the `link` package does not work if a `Connection` header is sent for the request since that's not an acceptable header for a push promise. That's due to all headers being passed from the request to the push promise.

It might be sensible not to pass any headers or to only pass the `Accept-Encoding` header.

It's a little bit weird because the request coming in is for an HTML page. The headers for that request will vary wildly from the headers you'd normally want for a different kind of asset (which is what push will usually provide.)

Maybe the headers need to be customized per the `as` attribute provided for a `Link` header? I can think of the generic type (no `as`) for XHR example: including the cookie headers may be required to authenticate the user with the backend.

**Comment by romainmenke** [comment]
`Maybe the headers need to be customized per the as attribute provided for a Link header? I can think of the generic type (no as) for XHR example: including the cookie headers may be required to authenticate the user with the backend.`

I really like that idea and will look into how this can work.

The reason all headers are passed at this point is because too much was breaking without any headers.

**Comment by romainmenke** [comment]
@jeromegn 

The most performant way to handle this would be to use the request header by default and only copy and modify when an offending header value is found.

The most controlled way would be to only pass on specific headers. This would mean allocations in your hot path.


Grabbed a list of common request headers to have a concrete set of headers to discuss. I marked the once I think are safe/useful to pass on. This list is obviously not complete, but is a starting point.

Alters Response / Server Behaviour:

- [x] Accept-Charset
- [x] Accept-Encoding
- [x] Accept-Language
- [x] Authorization
- [x] Cookie
- [x] DNT
- [x] User-Agent

Might be useful, but no strong opinion about these:

- [x] Host
- [x] Max-Forwards
- [x] Origin
- [x] Referer

Strip in Push Context:

- [ ] Accept
- [ ] Accept-Datetime
- [ ] Connection
- [ ] Content-Length
- [ ] Content-MD5
- [ ] Content-Type
- [ ] Date
- [ ] Expect
- [ ] Forwarded
- [ ] From
- [ ] If-Match
- [ ] If-Modified-Since
- [ ] If-None-Match
- [ ] If-Range
- [ ] If-Unmodified-Since
- [ ] Pragma
- [ ] Range
- [ ] Upgrade
- [ ] Warning
- [ ] Via

- [ ] Front-End-Https
- [ ] Proxy-Authorization
- [ ] Proxy-Connection
- [ ] TE
- [ ] X-ATT-DeviceId
- [ ] X-Correlation-ID
- [ ] X-Csrf-Token
- [ ] X-Forwarded-For
- [ ] X-Forwarded-Host
- [ ] X-Forwarded-Proto
- [ ] X-Http-Method-Override
- [ ] X-Request-ID
- [ ] X-Requested-With
- [ ] X-UIDH
- [ ] X-Wap-Profile

**Comment by jeromegn** [comment]
X-Forwarded-For would never happen because of the `CanPush` function.

I'm on the fence about the whole thing because these headers would come from the original request. They shouldn't necessarily be used for subsequent requests.

AFAICT, the only headers present should be the ones that would change the response. The issue is, there's no way to know them at that point.

I must be misunderstanding something. It's as if the http2 server needs to act like a browser when requesting these resources and build its own http headers for each type, like a browser would.

Anyway, thanks for looking into this :) I couldn't use this package at all before I commented out the line https://github.com/romainmenke/pusher/blob/master/link/link_go18.go#L95

What issues have you been seeing when not sending any headers? The tests stopped passing indeed when I removed that line. I started getting a few failures like:

```
initiate_push_test.go:48: bad options header
```

but those would be normal since I'm not sending the expected headers.

(I also removed the included `http2` folder.)

**Comment by romainmenke** [comment]
> X-Forwarded-For would never happen because of the CanPush function.

true, at the moment I make the assumption that the first proxy is responsible for initiating pushes, as there is no support for proxying push frames in Go yet. Not that every server is written in Go...

> (I also removed the included http2 folder.)

Nice, that is only there for tests, isn't used by the pkg itself.

> The tests stopped passing indeed when I removed that line. I started getting a few failures like:

That is indeed normal and expected. Until Push is supported in Go clients I can only write tests for every tiny part (so I did), instead of testing the actual functionality of this pkg.

What broke for us:
- compression (missing `Accept-Encoding`)
- auth (missing `Authorization`)
- everything relying on cookies

What was inconvenient to us:
- debugging (missing `User-Agent`)

It is true that the caller of `Push` starts a request that would otherwise come from the client and has to act a bit like a user-agent. I think that passing headers that are not tied to a specific request or content type is ok. As this pkg is intended to be used in a proxy it is unknown which headers are needed / used in origin servers, which is why I lean to allowing more than the bare minimum.

(split up the list of headers above into a couple of groups)

**Comment by romainmenke** [comment]
Also interesting from golang Proxy source code :

```go
// Hop-by-hop headers. These are removed when sent to the backend.
// http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html
var hopHeaders = []string{
	"Connection",
	"Proxy-Connection", // non-standard but still sent by libcurl and rejected by e.g. google
	"Keep-Alive",
	"Proxy-Authenticate",
	"Proxy-Authorization",
	"Te",      // canonicalized version of "TE"
	"Trailer", // not Trailers per URL above; http://www.rfc-editor.org/errata_search.php?eid=4522
	"Transfer-Encoding",
	"Upgrade",
}
```

**Comment by romainmenke** [comment]
@jeromegn I merged a fix for this issue. If that works for you I will close this issue. Looking forward to your feedback.

**Comment by jeromegn** [comment]
Great! I just tried it. Seems to have fixed the issues for me.

Thanks for quickly fixing this!
